name: Ejecución de tests de la práctica

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Instalar dependencias del proyecto
        run: npm ci
      - name: Ejecutar tests
        run: npm test

